### ISSUE TITLE
indentation for coffeescript?

### ISSUE THREAD

**Issue by MidnightP** [midnightsyntax/vscode-wrap-console-log#1]
Thanks for this very useful wrapper!

One issue I have though is that the console.log statement loses indentation in my coffeescript files. Is there a fix for this?

Cheers!

**Comment by midnightsyntax** [comment]
Thanks for your feedback!

At what action does the indentation break? Wrap down?
I have never used coffeescript to be honest but  i will look into this tonight so let me get back to you in a few hours.

**Comment by midnightsyntax** [comment]
Found a bug where the indentation would break on "Wrap down" to an empty existing row.
Will fix this and some other few bugs and update the extension. Should be ready later tonight.

**Comment by midnightsyntax** [comment]
This should now be fixed as of v1.3.2. 

Please let me know if the problem still exist.
Thanks again for your feedback!

**Comment by MidnightP** [comment]
It was on "wrap down" indeed. Thank you much!
