### ISSUE TITLE
Using multiple $txt in custom wrap text

### ISSUE THREAD

**Issue by fizzd** [midnightsyntax/vscode-wrap-console-log#10]
Hi, great extension, just what I was looking for! But I'd like to request if it were possible to make the $txt to work with multiple instances of it in the custom wrap text like so:

![2018-12-10_12-11-14](https://user-images.githubusercontent.com/10854458/49710676-e8171480-fc75-11e8-8fcc-30e9e64f1c9d.gif)

thank you!

**Comment by midnightsyntax** [comment]
This is now possible with version 1.7. :)

**Comment by fizzd** [comment]
thank you so much!
