### ISSUE TITLE
populating console.text

### ISSUE THREAD

**Issue by bluedusk** [midnightsyntax/vscode-wrap-console-log#12]
Dont know why but its populating console.text rather than console.log.

Latest VS code and plugin in windows10.

**Comment by Floriferous** [comment]
Had the same issue, you can now choose it from your VSCode settings:

Change `format.wrap.logFunctionName` and `format.wrap.prefixFunctionName` from console.text to console.log

**Comment by midnightsyntax** [comment]
This is now fixed with the 1.7.1 update.
Also, command 'console.log.wrap.string' now logs a string again. :)
