### ISSUE TITLE
Wrap down prefix not working properly since 1.7.0

### ISSUE THREAD

**Issue by Floriferous** [midnightsyntax/vscode-wrap-console-log#13]
Using the `Wrap down prefix console log` shortcut has been broken since 1.7.0 for me:

In this situation, putting your cursor on the `arg` inside the parenthesis does not do anything.

```js
export default stuff(
  otherStuff,
  a => (arg) => {
    const result = a + arg;
    return result;
  }
)
```

This one works:

```js
stuff(
  otherStuff,
  a => (arg) => {
    const result = a + arg;
    return result;
  }
)
```

**Comment by midnightsyntax** [comment]
I was not able to reproduce this. Please make sure you update to 1.7.2 since this release contains a fix that takes care of a problem that might be what caused your problem.
