### ISSUE TITLE
Logging with prefix does not add semicolon by default

### ISSUE THREAD

**Issue by pordemoni** [midnightsyntax/vscode-wrap-console-log#14]
After reading through some comments in the issues section, I did figure out how to automatically add semicolons after logs with prefixes. 

What I did was adding this line in VSCode's user settings.json:
`"wrap-console-log.format.wrap.prefixString": "$func('$var:', $var);`

The minor issue is that configuring this was not quite intuitive. A suggestion would be to add a setting which toggles adding semicolons automatically.

**Comment by midnightsyntax** [comment]
I totally agree that the configuration automatically needs an overhaul. I'm looking over it.
The setting `alwaysEndWithSemicolon` is being added to the upcoming version.

Thanks for your feedback!
