### ISSUE TITLE
Use spaces instead of tabs

### ISSUE THREAD

**Issue by Kalaschnik** [midnightsyntax/vscode-wrap-console-log#15]
ESLint complains, rightly, for the use of tabs instead of spaces:

![image](https://user-images.githubusercontent.com/9831678/57762120-29b55b00-76ff-11e9-8bce-decb359e2f64.png)

**Comment by midnightsyntax** [comment]
Thanks for reporting!
The indent is calculated from the line below the line where the "console.log" gets placed.
So if the line below have correct indentation the inserted one should too. Hm..

Are you using the latest version? 1.7.2

**Comment by Kalaschnik** [comment]
Ah, I’m using a different plugin; Turbo console log. Sorry for the confusion.
