### ISSUE TITLE
Can I change the shortcuts

### ISSUE THREAD

**Issue by Jonathanliu525** [midnightsyntax/vscode-wrap-console-log#18]
Hi, this is such an amazing tool that can help me debug my code. As I use the IntelliJ keymap, there is a short key conflict when I type cmd+L. Could you tell me if there is a way to change the default key shortcuts? Thank you

**Comment by PatricNox** [comment]
You can change the shortcuts through the keyboard shortcuts panel.

<img width="1005" alt="patric-example 2019-10-14 kl  14 44 26" src="https://user-images.githubusercontent.com/31646653/66752192-27fbe900-ee91-11e9-89e3-275fd399835d.png">

**Comment by midnightsyntax** [comment]
Yes you certainly can and thank you @Jonathanliu525 for the answer :heart:
