### ISSUE TITLE
set cursor on same line

### ISSUE THREAD

**Issue by MidnightP** [midnightsyntax/vscode-wrap-console-log#2]
Would it be nice to have the cursor set on the same line as the `console.log`? So let the cursor jump one line up or down. This allows you to immediately move the `console.log` line up or down.

**Comment by midnightsyntax** [comment]
Hm this could be an option for sure. Personally I like the way the cursor stays on the same line but I could implement a setting that say, make the cursor follow the insert and place itself behind `console.log`.

**Comment by MidnightP** [comment]
That would be awesome!

I'm trying out WebStorm at the moment but chances are I switch back to VS,
since WebStorm seems hard on coffeescript.

2017-09-14 16:15 GMT+02:00 midnightsyntax <notifications@github.com>:

**Comment by midnightsyntax** [comment]
I have added this to the extension. Enable it with the new setting "setCursorOnNewLine". Thanks for your feedback. :)
