### ISSUE TITLE
Change default key binding

### ISSUE THREAD

**Issue by MigHerCas** [midnightsyntax/vscode-wrap-console-log#23]
I personally find the keyboard shortcut a bit uncomfortable so I wonder if it's possible to change it. I haven't tweaked many extensions, so this might be a really basic question. 

Edit: I'm using a macbook (control + alt doesnt feel as smooth as in windows).

Thanks!

**Comment by midnightsyntax** [comment]
Oh I see. I have never typed on any kind of mac so I never though about it. 😶 You should be able to change the keybindings in the keybind settings of vscode.
