### ISSUE TITLE
create new line

### ISSUE THREAD

**Issue by MidnightP** [midnightsyntax/vscode-wrap-console-log#3]
If I do a [Down][Prefix] in my coffeescript on a line of code below which is an empty line, the console.log is placed on that empty line. 

I delete the console.log by deleting the whole line on which it is placed. This means that I loose the original empty line.

Can we have the extension alway create a new line? If the line below the selected code is not empty the extension will already do that for me.

**Comment by midnightsyntax** [comment]
This is now the default behavior in the extension. It will always create new lines except if the new setting "onEmptyLineAction" is set to "Replace".

**Comment by MidnightP** [comment]
+1
