### ISSUE TITLE
Add prefix input box not working?

### ISSUE THREAD

**Issue by niamleeson** [midnightsyntax/vscode-wrap-console-log#4]
Hello

The plugin is great, but I don't know if the show prefix input is working as intended. When you type in a custom string, the extension interprets it as a variable instead of prepending a string in the console.log.

**Comment by midnightsyntax** [comment]
Thanks for reporting this bug! I will look it up and get back to you.

**Comment by midnightsyntax** [comment]
This has now been fixed as of 1.6.1. Thanks again for the bug report! :)
