### ISSUE TITLE
Any way to remove semicolon?

### ISSUE THREAD

**Issue by siddrajpoot** [midnightsyntax/vscode-wrap-console-log#6]
I was wondering if there was a way to exclude the semicolon from the wraps?

Thanks!

**Comment by midnightsyntax** [comment]
Thanks for your question!
I will create an option for this in the next release.

**Comment by midnightsyntax** [comment]
lol I totally forgot about but you can edit the "console log text" manual with the setting "wrap-console-log.wrapText". :) Edit the setting in your User settings file and remove the semicolon at the end to solve your issue. The default value is  "console.log($txt);" but you can edit it to anything as long as "$txt" is in the string.
