### ISSUE TITLE
Feature request: customizable function name

### ISSUE THREAD

**Issue by WooodHead** [midnightsyntax/vscode-wrap-console-log#7]
In my usage scenario, I use
`debug('variable', variable);`  
instead of 
`console.log('variable', variable)`, 
so I can leave log info in the code and control it with a switch variable.

**Comment by midnightsyntax** [comment]
There is a setting called `wrap-console-log.wrapText` that enables custom wrap text but that setting is only used for the standard single wrap text without variable names.
The default value for `wrap-console-log.wrapText` is:

> {
> "wrap-console-log.wrapText": "console.log($txt);"
> }

Would a setting like `wrap-console-log.wrapPrefixText` satisfy your needs?
As of now that would mean the current default value world be something like:

> {
> "wrap-console-log.wrapPrefixText": "console.log($str, $val)"
> }

Where `$str` would be replaced with the variable name as a string and `$val` would be replaced with the variable.

In your case this would mean that you could change this value to:
> {
> "wrap-console-log.wrapPrefixText": "debug($str, $val)"
> }

Would this help you out?

**Comment by WooodHead** [comment]
Is 'debug' hard coded? Is it possible to add a option:
`"wrap-console-log.wrapFunctionName": "debug"`,
output--> `debug('variable', variable);`

So user can give any function name:
`"wrap-console-log.wrapFunctionName": "warn"`
output--> `warn('variable', variable);`

**Comment by WooodHead** [comment]
I forked the project and added 'functionName' feature, https://github.com/WooodHead/vscode-wrap-console-log-simple

**Comment by midnightsyntax** [comment]
This is now possible with 1.7. :)

**Comment by WooodHead** [comment]
Great, thanks for your work.
